class ProtoFileEnum {
public constructor() {}
public static fish:string = ''
+'syntax="proto3";\n'
+'package Proto.Model;\n'
+'message Msgs{\n'
+'    repeated Msg msgList = 1;\n'
+'}\n'
+'message Msg{\n'
+'    uint32 action = 1;\n'
+'    bytes  msgBody = 2;\n'
+'    string token = 3;\n'
+'}\n'
+'message Heartbeat { //心跳消息\n'
+'}\n'
+'message CommonStatus {\n'
+'    int32 code = 1;//0.表示登陆失败;5.表示被人挤掉\n'
+'    string msg = 2;\n'
+'}\n'
+'message BroadcastMessage {      //服务器端返回\n'
+'    uint32 broadType = 1;//类型1活动广告，2房间捕鱼\n'
+'    string msg = 2;//广告内容\n'
+'    uint32 langId = 3;//语言ID\n'
+'    repeated string params = 4;//语言ID对应的参数\n'
+'    uint32 priority = 5;//显示优先级\n'
+'}\n'
+'message BroadcastMessageList { //服务器端返回\n'
+'    repeated BroadcastMessage messageList = 1;//跑马灯广告列表	\n'
+'}\n'
+'message ExchangeGoodsItem { //服务器端返回\n'
+'    uint32 id = 1;//兑换货品id\n'
+'    string name = 2;\n'
+'    uint32 type = 3;//游戏中的物品：0;话费：1;京东卡：2;实物：3\n'
+'    uint32 exchangePriceId = 4;//货币在游戏里item表中的id\n'
+'    uint32 exchangePrice = 5;\n'
+'    string instruction = 6;\n'
+'    uint32 marketPrice = 7;\n'
+'    string url = 8;\n'
+'    uint32 minVip = 9;\n'
+'    uint32 goodsId = 10;//0表示实物\n'
+'    uint32 goodsNum = 11;\n'
+'    int32 serverNum = 12;//服务器剩余数量\n'
+'    int32 loopRecordColor = 13;//循环播放的兑换记录的文字颜色\n'
+'    uint32 orders = 14;//排序序号\n'
+'    uint32 minGunId = 15;//可兑换最小炮倍\n'
+'    uint32 isBling = 16;//是否闪光\n'
+'}\n'
+'message ExchangeGoodsRes { //服务器端返回\n'
+'    repeated ExchangeGoodsItem itemList = 1;\n'
+'}\n'
+'message ExchangeGoodsReq {\n'
+'//获取兑换商量列表（客户端调用）\n'
+'}\n'
+'message LoopExchangeRecord {\n'
+'    uint32 exchangeGoodsId = 1;//兑换货品id\n'
+'    string phone = 2;//手机\n'
+'    uint64 time = 3;//兑换时间\n'
+'}\n'
+'message LoopExchangeRecordsRes { //服务器端返回\n'
+'    repeated LoopExchangeRecord recordList = 1;\n'
+'}\n'
+'message LoopExchangeRecordsReq {\n'
+'//获取循环兑换记录（客户端调用）\n'
+'}\n'
+'message ActiveConfigMessage {   //活动\n'
+'    uint32 id = 1;//活动id\n'
+'    uint32 type = 2;//类型\n'
+'    uint32 startTime = 3;//开始时间\n'
+'    uint32 endTime = 4;//结束时间\n'
+'    uint32 activeState = 5;//活动状态  0: 过期;1: 正在进行;3: 暂停;\n'
+'    string parameter1 = 6;//参数1\n'
+'    string parameter2 = 7;//参数1\n'
+'    string descVip = 8;//特权描述\n'
+'    string nameUrl = 9;//名称Url\n'
+'    uint32 order = 10;//排序\n'
+'}\n'
+'message ActiveConfigMessageListRes {\n'
+'    repeated ActiveConfigMessage messageList = 1;\n'
+'}\n'
+'message ActiveConfigMessagesReq {\n'
+'}\n'
+'message LoginReq { //用户登录请求\n'
+'    uint32 userId = 1;\n'
+'    string account = 2;//账号字符串\n'
+'    uint32 platform = 3;//平台id\n'
+'    string secret = 4;//登陆服务器给的密钥\n'
+'}\n'
+'message LoginRes {     //登录成功后消息结构\n'
+'    PlayerInfo playerInfo = 1; // 用户信息\n'
+'    repeated TaskInfo taskInfo = 2;\n'
+'    repeated ItemInfo itemInfo = 3;//背包系统\n'
+'    uint32 systemTime = 4;//当前系统时间（单位秒）	\n'
+'    uint32 canReliefTime = 5;//救济金可领取时间，0为不在破产状态\n'
+'    uint32 everydayActive = 6;\n'
+'    uint32 everyWeekActive = 7;\n'
+'    uint32 newbieGuideId = 8;\n'
+'//    uint32 monthEndTime = 9;//月卡过期时间\n'
+'    MonthSignActiveInfo monthSignActiveInfo = 10;//月签到相关消息\n'
+'    uint32 isTodayFirstLogin = 11;//是否今日首次登录(0不是，1是)\n'
+'    uint32 isTodayDraw = 12;//是否进行了每日抽奖(0不是，1是)\n'
+'//    ActiveInfoMessage activeInfo = 13;//活动信息\n'
+'    string selfInviteCode = 14;//自己的邀请码\n'
+'}\n'
+'message TaskInfo {\n'
+'    int32 taskId = 1;	\n'
+'    int32 taskStatus = 2;\n'
+'    int32 curParameterValue = 3;\n'
+'}\n'
+'message MonthSignActiveInfo {\n'
+'    uint32 cumulativeSignTimes = 1;//累计签到次数\n'
+'    uint32 remainMakeUpTimes = 2;//剩余补签次数\n'
+'    uint32 isTodaySign = 3;//是否今天签到\n'
+'    uint32 isTodayMakeUp = 4;//是否今天补签\n'
+'    uint32 curMonth = 5;//当前月份\n'
+'}\n'
+'message LockRelation {\n'
+'    uint32 gunIndex = 1;\n'
+'    uint32 fishId = 2;\n'
+'}\n'
+'message ItemInfo {\n'
+'    uint32 itemId = 1;\n'
+'    uint32 totalCount = 2;\n'
+'    int32 expried = 3;// 过期时间\n'
+'}\n'
+'message PlayerInfo {\n'
+'    uint32 userId = 1;\n'
+'    string nickName = 2;//玩家昵称\n'
+'    string iconUrl = 3;//玩家头像\n'
+'    uint32 gems = 4;\n'
+'    uint64 coins = 5;\n'
+'    uint32 position = 6;	\n'
+'    uint32 gunId = 7;\n'
+'    uint32 maxGunId = 8;\n'
+'    repeated uint32 items = 9;//正在使用的锁定道具ID\n'
+'    repeated LockRelation lockRelation = 10;\n'
+'    uint32 roleLevel = 11;\n'
+'    uint32 roleExp = 12;\n'
+'    uint32 vipLevel = 13;\n'
+'    uint32 batterySkinId = 14;//炮台皮肤\n'
+'    uint32 gunrestSkinId = 15;//炮座皮肤\n'
+'    uint32 coupon = 16;//点券\n'
+'    uint32 totalChargeRMB = 17;//累计充值金额(单位是分)\n'
+'    string monthEndTime = 18;//月卡过期时间\n'
+'    string monthLastGetTime=19; //上一次领取月卡\n'
+'    uint32 gunPow = 20; //威力\n'
+'    uint32 signWeek=21; //签到第几周\n'
+'    string signLog=22;  //签到领取记录\n'
+'    string lastLoginDate = 23; //最后登录日期\n'
+'//    uint32 reliefNums = 24;//当日领取救济金的次数\n'
+'//    string reliefDate = 25;//最近一次领取救济金的日期\n'
+'    uint32 reliefAvailableTime = 24;//下一次领取救济金的时间戳\n'
+'}\n'
+'message RoomInfoReq {\n'
+'    uint32 type = 1; //请求进入房间类型\n'
+'    uint32 userId = 2;	//userId\n'
+'    int32 roomId = 3;\n'
+'}\n'
+'message RoomInfoRes {\n'
+'    uint32 flag = 1;\n'
+'    uint32 port = 2;\n'
+'    string ip = 3;\n'
+'    int32 roomId = 4;\n'
+'    uint32 type = 5;\n'
+'}\n'
+'message IntoRoomReq {\n'
+'    uint32 userId = 1;\n'
+'    string account = 2;//账号字符串\n'
+'    string identity = 3;	\n'
+'    uint32 roomId = 4;  //房间号\n'
+'    uint32 type = 5;\n'
+'    string password=6;\n'
+'}\n'
+'message IntoRoomRes {\n'
+'    uint32 flag = 1;\n'
+'    repeated PlayerInfo playerInfo = 2;\n'
+'}\n'
+'message RoomInfo {\n'
+'    uint32 roomId = 1;\n'
+'    uint32 userCount = 2;\n'
+'    uint32 type = 3;\n'
+'}\n'
+'message GetReliefMoneyReq {\n'
+'//申请领取救济金\n'
+'}\n'
+'//message GetReliefMoneyRes {\n'
+'//申请领取救济金状态\n'
+'//    int32 code = 1; //0 成功\n'
+'//    string msg = 2;\n'
+'//}\n'
+'message DailySignReq {\n'
+'//每日签到请求\n'
+'}\n'
+'//message DailySignRes {\n'
+'//每日签到请求\n'
+'//    int32 code = 1; //0 成功\n'
+'//    string msg = 2;\n'
+'//}\n'
+'message GetMonthAwardReq {\n'
+'    //领取月卡奖励\n'
+'}\n'
+'//message GetMonthAwardRes {\n'
+'    //领取月卡奖励状态\n'
+'//    int32 code = 1; //0 成功\n'
+'//    string msg = 2;\n'
+'//}\n'
+'message BuyMonthCardReq {\n'
+'    //购买月卡\n'
+'}\n'
+'message RoomServerInfo {\n'
+'    uint32 serverId = 1;\n'
+'    uint32 state = 2;//1流畅(0<100)，2繁忙(101<150)，3拥挤(151~180)，4满员(181~200)\n'
+'}\n'
+'message ManualChooseRoomReq {\n'
+'    int32 serverId = 1;\n'
+'}\n'
+'message ManualChooseRoomRes {\n'
+'    repeated RoomServerInfo serverInfo = 1;\n'
+'    repeated RoomInfo roomInfo = 2;\n'
+'}\n'
+'message VipLevelUp {\n'
+'    uint32 oldLevel = 1;\n'
+'    uint32 newLevel = 2;\n'
+'}\n'
+'message LevelUp {\n'
+'    uint32 oldLevel = 1;\n'
+'    uint32 newLevel = 2;\n'
+'    uint32 userId = 3;//升级玩家\n'
+'}\n'
+'message FishingGunReq {\n'
+'    uint32 angle = 1;\n'
+'    uint32 gunIndex = 2;//枪械索引\n'
+'    uint32 bulletId = 3;//子弹id\n'
+'}\n'
+'message FishingGunRes {\n'
+'    uint32 userId = 1;\n'
+'    FishingGunReq gun = 2;\n'
+'}\n'
+'message FishingHitReq {\n'
+'    uint32 fishId = 1;\n'
+'    uint32 bulletId = 2;//子弹id\n'
+'    repeated uint32 nettingFishs = 3; //被网中的鱼\n'
+'}\n'
+'message FishingHit{\n'
+'    uint32 userId = 1;\n'
+'    uint32 fishId = 2;\n'
+'    repeated GetItem getItems = 3;\n'
+'}\n'
+'message RandomFishHitRes {\n'
+'    uint32 userId = 1;\n'
+'    uint32 fishFunctionType = 2;//0一网打尽\n'
+'    uint32 fishId = 3;//击杀的鱼id\n'
+'    repeated FishingHit fishingHitback = 4;//被波及而死的鱼命中信息\n'
+'}\n'
+'message GetItem {\n'
+'    uint32 itemId = 1;\n'
+'    uint32 count = 2;\n'
+'    int32 expried = 3;// 过期时间\n'
+'}\n'
+'message PondFishes {\n'
+'    repeated AddFish fishes = 1; \n'
+'}\n'
+'message AddFish {\n'
+'    uint32 type = 1;\n'
+'    uint32 fishId = 2;\n'
+'    uint32 pathId = 3;\n'
+'    repeated uint32 uniId = 4;\n'
+'    Coordinate coordinate = 5;\n'
+'    uint32 aliveTime = 6;//还能活多久\n'
+'}\n'
+'message Coordinate {\n'
+'    int32 xvalue = 1;\n'
+'    int32 yvalue = 2;\n'
+'}\n'
+'message PondState {\n'
+'    uint32 type = 1;\n'
+'    uint32 fishId = 2;\n'
+'    uint32 userId = 3;\n'
+'}\n'
+'message GunFishPosInfoMessage {\n'
+'    repeated FishPosInfo fishPostList =1;\n'
+'}\n'
+'message FishPosInfo {\n'
+'    uint32 groupId = 1;\n'
+'    repeated uint32 fishId = 2;\n'
+'    uint32 pos = 3;\n'
+'}\n'
+'message UseItemReq {\n'
+'    uint32 itemId = 1;\n'
+'}\n'
+'message UseItemRes {\n'
+'    uint32 userId = 1;\n'
+'    uint32 itemId = 2;	//道具id\n'
+'    AddFish addFish = 3;//有鱼加鱼，没有鱼type,fishId,pathId,uniId都是-1，但随一个位置\n'
+'    uint32 state = 4;	//使用状态:原因是既没物品又没钱为0,1是成功,鱼潮来临前使用错误代码为4,狂暴使用等级不够错误代码为2,用狂暴、分身的时候不能用锁定为3\n'
+'    repeated uint32 frozenFishIds = 5;//冰冻的鱼id\n'
+'}\n'
+'message ChangeGunReq {\n'
+'    uint32 type = 1;    //1表示改变炮倍（gunId），2表示改变威力（power），3换皮肤（skinId）, 5 卸下皮肤\n'
+'    uint32 skinId = 2;\n'
+'    uint32 changeValue = 3;   //改变后的数值\n'
+'}\n'
+'message ChangeGunRes {\n'
+'    uint32 userId = 1;\n'
+'    uint32 type = 2;\n'
+'    uint32 gunId = 3;\n'
+'    uint32 skinId = 4;\n'
+'    uint32 state = 5;//0失败，1成功\n'
+'    uint32 power = 6;\n'
+'}\n'
+'message UseWarheadReq {\n'
+'    uint32 itemId = 1;//弹头id\n'
+'    uint32 uniId = 2;//死哪条鱼\n'
+'}\n'
+'message UseWarheadRes {\n'
+'    uint32 userId = 1;//谁打的\n'
+'    uint32 uniId = 2;//打死了哪条鱼\n'
+'    uint32 addCoins = 3;//加了多少钱\n'
+'}\n'
+'message UseLockItem {\n'
+'    uint32 itemId = 1;//锁定卡,分身,狂暴的道具id\n'
+'    uint32 fishId = 2;//锁定的鱼id\n'
+'    uint32 userId = 3;//使用人id\n'
+'    uint32 gunIndex = 4;//枪械索引\n'
+'}\n'
+'message LockItemEnd {\n'
+'    uint32 itemId = 1;//锁定卡,分身,狂暴的道具id\n'
+'    uint32 userId = 2;//使用人id \n'
+'}\n'
+'message QuitRoom {\n'
+'    uint32 position = 1;\n'
+'    uint32 userId = 2;\n'
+'}\n'
+'message MajorParameterChange {\n'
+'    uint32 userId = 1;\n'
+'    uint64 coins = 2;\n'
+'    uint32 gems = 3;\n'
+'    uint32 level = 4;\n'
+'    repeated ItemInfo item = 5;\n'
+'    uint32 coupon = 6;//点券\n'
+'    uint32 signWeek=7; //签到第几周\n'
+'    string signLog=8;  //签到领取记录\n'
+'//    uint32 reliefNums = 10;//当日领取救济金的次数\n'
+'//    string reliefDate = 11;//最近一次领取救济金的日期\n'
+'    uint32 reliefAvailableTime = 12;//下一次领取救济金的时间戳\n'
+'    string monthEndTime = 13;//月卡过期时间\n'
+'    string monthLastGetTime=14; //上一次领取月卡\n'
+'}\n'
+'message UserBalanceRes {\n'
+'    uint32 userId = 1;\n'
+'    uint64 coins = 2;\n'
+'    uint32 gems = 3;\n'
+'}\n'
+'////////////////////////////////////\n'
+'message Bankrupt {\n'
+'    uint32 state = 1;//0破产;1到点了领取;2时间不到;3.又有钱了,救济CD解除;4向server传了state!=0;5.今日领取已达上限;6.金币>0;7.领取救济金\n'
+'    uint32 canReliefTime = 2;//救济金可领取时间\n'
+'    uint32 coins = 3;//成功时,返回救济金\n'
+'    uint32 userId = 4;//向其他玩家显示\n'
+'}\n'
+'message ShopBuyReq {\n'
+'        uint32 shopId =1;//购买的商城表ID\n'
+'}\n'
+'message ShopBuyRes {\n'
+'        uint32 state = 1;//0因为货币不足失败，1成功，2背包满\n'
+'}\n'
+'message FindUserReq {\n'
+'        uint32 userId = 1;\n'
+'}\n'
+'message FindUserRes {\n'
+'        uint32 state = 1;//0:查无此人,userName放"";1:有这人，这时候userName是玩家name;\n'
+'        string receiveUserName = 2;\n'
+'}\n'
+'message GiveItemReq {\n'
+'        uint32 receiveUserId = 1;//接收方的userID\n'
+'        uint32 itemId = 2;// 赠送的物品 id\n'
+'        uint32 totalCount = 3;// 赠送的物品 数量\n'
+'}\n'
+'message GiveItemRes {\n'
+'        uint32 state = 1;//0;赠送方物品不足；1:赠送成功；2:接收方背包满了；3:赠送方赠送次数满了；4:接收方接收次数满了\n'
+'}\n'
+'message SellItemReq {\n'
+'        uint32 sellitemId = 1;// 出售物品id\n'
+'        uint32 sellCount = 2;// 出售物品数量\n'
+'}\n'
+'message SellItemRes {\n'
+'        uint32 state = 1;//0;出售物品不足；1:出售成功；\n'
+'}\n'
+'message ItemProto {\n'
+'    uint32 itemId = 1;\n'
+'    uint32 count = 2;\n'
+'    int32 expried = 3;// 过期时间\n'
+'}\n'
+'message UpgradeOrForgeReq {\n'
+'        uint32 type = 1;//1解锁，2无精华锻造，3有精华锻造\n'
+'}\n'
+'message UpgradeOrForgeRes {\n'
+'    uint32 state = 1;//0类型不对，1成功(成功才有下面的optional)，2材料不够，3倍数已达上限，4锻造但失败了\n'
+'    uint32 type = 2;\n'
+'    uint32 userId = 3;\n'
+'    uint32 afterGunId = 4;      //锻造后的gun id\n'
+'    ItemProto itemProto = 5;\n'
+'}\n'
+'message RankDataMessage {\n'
+'        int32 rankType = 1;//排行类型1等级 2金币\n'
+'        int32 rank = 2;//排名\n'
+'        int32 userId = 3;//玩家ID\n'
+'        int32 roleLevel = 4;//玩家等级\n'
+'        int32 vipLevel = 5;//玩家VIP等级	\n'
+'        int64 rankValue = 6;//排行对应的值\n'
+'        string name = 7;//玩家昵称\n'
+'        string iconUrl = 8;//头像\n'
+'}\n'
+'message GetRankDataReq {\n'
+'        int32 rankType = 1;//排行类型1等级 2金币\n'
+'}\n'
+'message GetRankDataRes {\n'
+'        repeated RankDataMessage ranklist = 1;//排行数据\n'
+'}\n'
+'message WorldBossInfo {\n'
+'        uint32 bossId = 1;//世界BossID\n'
+'        uint32 fishId = 2;//鱼ID，不是UID\n'
+'        uint32 state = 3;//当前状态0要来了 1在池塘中 2消失倒计时 3死亡 4 扩盾减少\n'
+'        uint32 time = 4; //倒计时秒\n'
+'        uint32 shieldMax = 5;//扩盾最大值\n'
+'        uint32 curShieldValue = 6;//扩盾当前值从0开始\n'
+'        uint32 userId = 7;//userId\n'
+'        repeated ItemProto items = 8;//获取的金币\n'
+'}\n'
+'message DrawLotteryReq {\n'
+'    uint32 gear = 1;//抽奖的档位0——5\n'
+'}\n'
+'message DrawLotteryRes {\n'
+'    uint32 userId = 1;\n'
+'    uint32 state = 2;//0杀死奖金鱼不够，1成功，2积分不足，3前后应领档位不同, 4鱼券限制不足\n'
+'        uint32 itemIndex = 3;//获得的奖品(0~5)\n'
+'}\n'
+'message LotteryConditonAccumulate {\n'
+'        uint32 integral = 1;//当前积分\n'
+'        uint32 killNum = 2;//当前击杀数目\n'
+'        uint32 todayDrawTimes = 3;//今天抽奖次数\n'
+'}\n'
+'message FishingHitRes {\n'
+'    repeated FishingHit fishingHit=1;\n'
+'}\n'
+'message FishingUnlockStatus {\n'
+'     uint32 type = 1;\n'
+'}\n'
+'message EmailInfo{\n'
+'    uint32 emailId = 1;\n'
+'    string emailTitle = 2;\n'
+'    string emailContent = 3;\n'
+'    uint32 itemType = 4;// 0:没有要领取附件 1:有需要领取附件\n'
+'    uint32 type = 5;// 0:已读 1:未读\n'
+'    repeated ItemInfo itemInfo = 6;\n'
+'    uint32 expire = 7;\n'
+'}\n'
+'message EmailListReq{}\n'
+'message EmailListRes {\n'
+'    uint32 totalNum = 1; // 邮件数量 \n'
+'    repeated EmailInfo emailInfo = 2;\n'
+'}\n'
+'message EmailOperationReq {\n'
+'    uint32 type = 1;             // 1:领取附件 2:删除邮件 3:读取邮件\n'
+'    repeated uint32 emailId = 2; // 领取附件邮件id\n'
+'}\n'
+'message EmailOperationRes {\n'
+'    uint32 type = 1;             // 1:领取附件 2:删除邮件 3:读取邮件\n'
+'    repeated uint32 emailId = 2; // 已处理id\n'
+'}\n'
+'message NoticeInfo{\n'
+'    uint32 noticeId=1;\n'
+'    string noticeTitle=2;\n'
+'    string noticeContent=3;\n'
+'    uint32 noticeType=4; // 1：纯文字型，2：图片型\n'
+'}\n'
+'message NoticeListReq{}\n'
+'message NoticeListRes{\n'
+'    repeated NoticeInfo noticeInfo=1;\n'
+'}\n'
+'message RankInfo{\n'
+'    uint32 rankOrder=1;// 榜单排名\n'
+'    uint32 userId=2;\n'
+'    string userName=3;\n'
+'    string headUrl=4;\n'
+'    uint32 rankNum=5;// 排行依据\n'
+'    repeated ItemInfo awardInfo=6;// 奖励信息\n'
+'}\n'
+'message RankReq{\n'
+'    uint32 type=1; // 1 金币榜单 2 收益榜单 3 竞技日榜 4 竞技周榜\n'
+'}\n'
+'message RankRes{// 排行榜\n'
+'    RankInfo selfRankInfo=2;// 本人榜单信息\n'
+'    repeated RankInfo rankInfo=3;// 榜单信息\n'
+'}\n';
}